name: Secret Scanner
run-name: TruffleHog is scanning ${{ github.repository }} for secrets

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

jobs:
  trufflehog-scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified
